greenplum:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 10.21.1.70
      user: read_only
      password: "{{ env_var('COREDW_RO_PASSWORD','COREDW_RO_PASSWORD') }}"
      port: 5432
      dbname: coredw
      schema: test2
      threads: 4

clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: summarydata
      host: 10.4.34.182
      port: 8123
      user: r2ds
      password: "{{ env_var('CHAPI_PASS','CHAPI_PASS') }}"
      secure: False

spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: ip-10-1-128-194.us-west-2.compute.internal
      port: 10001
