


Docker-Build:
  title: Building docker image
  type: build
  working_directory: '${{CLONE_STEP_NAME}}'
  arguments:
    image_name: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    tag: latest


Push:
  type: push
  arguments:
    candidate: '${{build_step_name}}'
    tag: latest
    image_name: codefresh/app
    registry: my-registry

