version: "1.0"
stages:
  - "clone"
  - "build-docker-image"

steps:
  clone:
    title: "Clone repository"
    type: "git-clone"
    repo: "SteelHouse/dbt_data_quality"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  docker-image:
    title: "Build Docker image"
    stage: "build-docker-image"
    type: "build"
    image_name: 'steelhousedev/${{CF_REPO_NAME}}'
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: 'Dockerfile'
